### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by choudhurym**

### CODE REVIEW

**Comment by ibnesayeed** [comment]
* Change file name to `aws_server_setup_in_docker_by_muntabir.pdf`
* Change the title slide to reflect the fact that you are setting up a web service on AWS in Docker
* Towards the end, demonstrate that your service is running and accessible from elsewhere using `telnet`
* Hyperlinks are often lost when slides are printed, so make sure to include full URI as a sub-bullet or in the footer of corresponding slides

**Comment by choudhurym** [comment]
Hello Sawood,

I made the changes. Please review and let me know if I need to change/add any additional things.
Thank you.

**Comment by ibnesayeed** [comment]
This looks good, but a few changes before we merge it:

* Remove the old file using something like `git rm AWS.pdf` and commit changes
* Update the last slide's screenshot to illustrate a message that was echoed back from the server after telnet

**Comment by choudhurym** [comment]
Modified the last slide's screenshot and now it is illustrating that a message is echoed back from the server. Also deleted the previous pdf. 

Thank you,
Muntabir

**Comment by ibnesayeed** [comment]
I am merging this. I may ask you to walk through your slides tomorrow after main lecture slides are over.

**Comment by choudhurym** [comment]
Sure, No problem sir!

**Pull request merged**
